networks:
  backend:
    external: true
    name: backend

services:
  dagster_wpr:
    build:
      context: ..
      dockerfile: docker/Dockerfile_wpr
    image: wpr_image
    container_name: dagster_wpr
    # restart: unless-stopped
    restart: no
    environment:
      DAGSTER_SQL_ALCHEMY_DB_URL: postgresql+psycopg2://$PG_USER:$PG_PASSWORD@dagster_postgres:5432/$PG_DB
      MONGO_URI: mongodb://mongodb_dagster:27017/
      MONGO_DB: $MONGO_DB
      MONGO_LANDING_COL: $MONGO_LANDING_COL
      MONGO_PROCESSED_COL: $MONGO_PROCESSED_COL
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: $MINIO_ACCESS_KEY
      MINIO_SECRET_KEY: $MINIO_SECRET_KEY
      LANDING_BUCKET: $LANDING_BUCKET
      CLEAN_BUCKET: $CLEAN_BUCKET
    ports:
      - "3000:3000"
    volumes:
      - ../dagster_home:/app/dagster_home
    networks: [backend]
